project:
  type: website
  output-dir: _outputs/html
  resources:
    - resources/**
    - status/**

profile:
  default: html

website:
  title: "Ingeniería Asistida por Sistemas Inteligentes"
  page-navigation: true
  search: false

  announcement:
    dismissable: false
    content: "![](/resources/images/ants.png){.iasi-ants-image}"
    type: light
    position: above-navbar

  navbar:
    title: IASI

    left:
      - text: "Libros"
        menu:
          - text: "Todos"
            href: books.qmd
          - text: "IASI I"
            href: books.qmd#iasi-i
          - text: "IASI II"
            href: books.qmd#iasi-ii
          - text: "IASI III"
            href: books.qmd#iasi-iii
      - text: "Manuales"
        menu:
          - text: "Todos"
            href: manuals.qmd
          - text: "User Guides"
            href: manuals/user-guides.qmd
          - text: "Technical Guides"
            href: manuals/technical-guides.qmd
      - text: "Artefactos"
        menu:
          - text: "Todos"
            href: artifacts.qmd
          - text: "IASI Quarto"
            href: artifacts/iasi-quarto.qmd
          - text: "IASI Lua"
            href: artifacts/iasi-lua.qmd
          - text: "IASI Tools Dev"
            href: artifacts.qmd#iasi-tools-dev
      - text: "Principios"
        href: principles.qmd
      - text: "Manifiesto"
        href: common/manifesto.qmd
    right:
      - text: "ES"
        href: index.qmd
        aria-label: "Español"
      - text: "EN"
        href: en/index.qmd
        aria-label: "English"
    tools:     
      - icon: translate
        href: common/manifesto-bilingual.qmd
        aria-label: "Idioma / Language"    
      - icon: envelope
        href: common/contact.qmd
        aria-label: "Contact us"
      - icon: github
        href: https://github.com/iasi-org
        aria-label: "Explore IASI on GitHub"
