project:
  type: website
  output-dir: _outputs/html
  resources:
    - resources/**
    - status/**

profile:
  default: html

website:
  title: "Ingeniería Asistida por Sistemas Inteligentes"
  page-navigation: true
  search: false

  announcement:
    dismissable: false
    content: "![](/resources/images/ants.png){.iasi-ants-image}"
    type: light
    position: above-navbar

  navbar:
    title: IASI

    left:
      - text: "Manifiesto"
        href: manifesto.qmd
      - text: "Principios"
        href: principles.qmd
      - text: "Artefactos"
        href: artifacts.qmd
    right:
      - text: "ES"
        href: index.qmd
        aria-label: "Español"
      - text: "EN"
        href: en/index.qmd
        aria-label: "English"
    tools:     
      - icon: translate
        href: manifesto-bilingual.qmd
        aria-label: "Idioma / Language"    
      - icon: envelope
        href: contact.qmd
        aria-label: "Contact us"
      - icon: github
        href: https://github.com/iasi-org
        aria-label: "Explore IASI on GitHub"
