format:
  html:
    theme: cosmo
    css:
      - resources/css/iasi.css
      - resources/css/styles.css
      - resources/css/styles-artifacts.css    
    toc: false
    page-layout: full
    smooth-scroll: true
    include-in-header:
      - includes/language.html
