project:
  type: website
  output-dir: _outputs/html
  resources:
    - resources/**

profile:
  default: html

website:
  title: "IASI"
  page-navigation: true
  search: false

  announcement:
    dismissable: false
    content: "![](/resources/images/ants.png){.iasi-ants-image}"
    type: light
    position: above-navbar
